### ISSUE TITLE
Do you happen to have the HMMs for V-Xtractor? 

### ISSUE THREAD

**Issue by apredeus** [carden24/Bioinformatics_scripts#4]
Dear Eric, 

I've noticed you have the V-Xtractor script in your collection. The official page for the tool is long gone, so there's nowhere to download the original files from. Do you happen to have the HMMs necessary for the annotator to work? 

Thank you in advance! 

-- Alex

**Comment by LeeBergstrand** [comment]
@apredeus https://github.com/carden24/V-Xtractor

**Comment by apredeus** [comment]
Oh, completely overlooked that. Google only found the one script. Thank you very much!

**Comment by carden24** [comment]
Glad the issue resolved itself quickly (Thanks, Lee). I will add a link to the lab repository to make it easier. Thanks for your interest in the paper.
Erick
